### PR TITLE
Let the post-transaction hook run after depmod

### LINKED ISSUE #2: Failing restore hook due to existing modules directory
The restore hook fails for me because `/usr/lib/modules/${KVER}` is not removed until after `10-linux-modules-post.hook` is run. Any idea as to why this is happening?

<details>

```
[2022-09-02T15:11:00+0200] [PACMAN] starting full system upgrade
[2022-09-02T15:11:22+0200] [ALPM] running '10-linux-modules-pre.hook'...
[2022-09-02T15:11:22+0200] [ALPM-SCRIPTLET] ++ uname -r
[2022-09-02T15:11:22+0200] [ALPM-SCRIPTLET] + KVER=5.19.5-arch1-1
[2022-09-02T15:11:22+0200] [ALPM-SCRIPTLET] + test -d /usr/lib/modules/5.19.5-arch1-1
[2022-09-02T15:11:22+0200] [ALPM-SCRIPTLET] + mkdir -p /usr/lib/modules/backup
[2022-09-02T15:11:22+0200] [ALPM-SCRIPTLET] + cp -an --reflink=auto /usr/lib/modules/5.19.5-arch1-1 /usr/lib/modules/backup/
[2022-09-02T15:11:23+0200] [ALPM] running '60-mkinitcpio-remove.hook'...
[2022-09-02T15:11:23+0200] [ALPM] running '71-dkms-remove.hook'...
[2022-09-02T15:11:23+0200] [ALPM-SCRIPTLET] Deprecated feature: REMAKE_INITRD
[2022-09-02T15:11:23+0200] [ALPM-SCRIPTLET] Deprecated feature: REMAKE_INITRD
[2022-09-02T15:11:23+0200] [ALPM-SCRIPTLET] ==> dkms remove --no-depmod v4l2loopback/0.12.5 -k 5.19.5-arch1-1
[2022-09-02T15:11:23+0200] [ALPM-SCRIPTLET] Deprecated feature: REMAKE_INITRD
[2022-09-02T15:11:23+0200] [ALPM-SCRIPTLET] ==> depmod 5.19.5-arch1-1
[2022-09-02T15:11:25+0200] [ALPM] transaction started
[2022-09-02T15:11:27+0200] [ALPM] upgraded linux (5.19.5.arch1-1 -> 5.19.6.arch1-1)
[2022-09-02T15:11:30+0200] [ALPM] upgraded linux-headers (5.19.5.arch1-1 -> 5.19.6.arch1-1)
[2022-09-02T15:11:31+0200] [ALPM] transaction completed
[2022-09-02T15:11:32+0200] [ALPM] running '10-linux-modules-post.hook'...
[2022-09-02T15:11:32+0200] [ALPM-SCRIPTLET] ++ uname -r
[2022-09-02T15:11:32+0200] [ALPM-SCRIPTLET] + KVER=5.19.5-arch1-1
[2022-09-02T15:11:32+0200] [ALPM-SCRIPTLET] + test -d /usr/lib/modules/backup/5.19.5-arch1-1
[2022-09-02T15:11:32+0200] [ALPM-SCRIPTLET] + test -d /usr/lib/modules/5.19.5-arch1-1
[2022-09-02T15:11:32+0200] [ALPM-SCRIPTLET] + rm -rf /usr/lib/modules/backup
[2022-09-02T15:11:32+0200] [ALPM] running '30-systemd-update.hook'...
[2022-09-02T15:11:32+0200] [ALPM] running '60-depmod.hook'...
[2022-09-02T15:11:33+0200] [ALPM] running '70-dkms-install.hook'...
[2022-09-02T15:11:33+0200] [ALPM-SCRIPTLET] ==> dkms install --no-depmod v4l2loopback/0.12.5 -k 5.19.6-arch1-1
[2022-09-02T15:11:34+0200] [ALPM-SCRIPTLET] Deprecated feature: REMAKE_INITRD
[2022-09-02T15:11:36+0200] [ALPM-SCRIPTLET] ==> depmod 5.19.6-arch1-1
[2022-09-02T15:11:37+0200] [ALPM] running '90-mkinitcpio-install.hook'...
[2022-09-02T15:11:37+0200] [ALPM-SCRIPTLET] ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'default'
[2022-09-02T15:11:37+0200] [ALPM-SCRIPTLET]   -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
[2022-09-02T15:11:37+0200] [ALPM-SCRIPTLET] ==> Starting build: 5.19.6-arch1-1
[2022-09-02T15:11:37+0200] [ALPM-SCRIPTLET]   -> Running build hook: [base]
[2022-09-02T15:11:38+0200] [ALPM-SCRIPTLET]   -> Running build hook: [udev]
[2022-09-02T15:11:38+0200] [ALPM-SCRIPTLET]   -> Running build hook: [plymouth]
[2022-09-02T15:11:38+0200] [ALPM-SCRIPTLET]   -> Running build hook: [autodetect]
[2022-09-02T15:11:38+0200] [ALPM-SCRIPTLET]   -> Running build hook: [modconf]
[2022-09-02T15:11:38+0200] [ALPM-SCRIPTLET]   -> Running build hook: [block]
[2022-09-02T15:11:38+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: xhci_pci
[2022-09-02T15:11:39+0200] [ALPM-SCRIPTLET]   -> Running build hook: [filesystems]
[2022-09-02T15:11:39+0200] [ALPM-SCRIPTLET]   -> Running build hook: [plymouth-encrypt]
[2022-09-02T15:11:39+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: qat_4xxx
[2022-09-02T15:11:39+0200] [ALPM-SCRIPTLET]   -> Running build hook: [keyboard]
[2022-09-02T15:11:39+0200] [ALPM-SCRIPTLET]   -> Running build hook: [fsck]
[2022-09-02T15:11:39+0200] [ALPM-SCRIPTLET] ==> Generating module dependencies
[2022-09-02T15:11:39+0200] [ALPM-SCRIPTLET] ==> Creating zstd-compressed initcpio image: /boot/initramfs-linux.img
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET] ==> Image generation successful
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET] ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'fallback'
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET]   -> -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-fallback.img -S autodetect
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET] ==> Starting build: 5.19.6-arch1-1
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET]   -> Running build hook: [base]
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET]   -> Running build hook: [udev]
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET]   -> Running build hook: [plymouth]
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET]   -> Running build hook: [modconf]
[2022-09-02T15:11:40+0200] [ALPM-SCRIPTLET]   -> Running build hook: [block]
[2022-09-02T15:11:41+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: aic94xx
[2022-09-02T15:11:41+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: bfa
[2022-09-02T15:11:41+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: qed
[2022-09-02T15:11:41+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: wd719x
[2022-09-02T15:11:41+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: qla2xxx
[2022-09-02T15:11:41+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: qla1280
[2022-09-02T15:11:41+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: xhci_pci
[2022-09-02T15:11:42+0200] [ALPM-SCRIPTLET]   -> Running build hook: [filesystems]
[2022-09-02T15:11:42+0200] [ALPM-SCRIPTLET]   -> Running build hook: [plymouth-encrypt]
[2022-09-02T15:11:42+0200] [ALPM-SCRIPTLET] ==> WARNING: Possibly missing firmware for module: qat_4xxx
[2022-09-02T15:11:43+0200] [ALPM-SCRIPTLET]   -> Running build hook: [keyboard]
[2022-09-02T15:11:43+0200] [ALPM-SCRIPTLET]   -> Running build hook: [fsck]
[2022-09-02T15:11:44+0200] [ALPM-SCRIPTLET] ==> Generating module dependencies
[2022-09-02T15:11:44+0200] [ALPM-SCRIPTLET] ==> Creating zstd-compressed initcpio image: /boot/initramfs-linux-fallback.img
[2022-09-02T15:11:44+0200] [ALPM-SCRIPTLET] ==> Image generation successful
```
</details>

### PR DESCRIPTION
**Pull request by hrdl-github**
depmod must remove the module directory before the backup is restored, as required by the check introduced in 96589eeff0e28d44846f9973500dd09bb11db747. On another note, this check might be too strict, as depmod will not remove the module directory if it is not empty, e.g. because of manually added modules. This was not an issue before because the existence of the target directory was not relevant to the restoration of the backup.

Fixes https://github.com/lideming/kernel-modules-hook-reflink/issues/2.

### CODE REVIEW

**Comment by lideming** [comment]
LGTM. Thanks for your investigation! Sorry that I usually reboot my arch after upgrading so I didn't see the problem :(

**Comment by lideming** [comment]
> this check might be too strict, as depmod will not remove the module directory if it is not empty

Do you have way around this? I think we can:
- remove the check, or
- check for the existence of specific file in the target directory

**Comment by hrdl-github** [comment]
Any files installed by the package should do, including `vmlinuz`. The only case I can think of right now that would warrant a check would be the installation of a package that provides modules for the currently running kernel, e.g. a self-built package that provides `vmlinuz` (to trigger the hook's `Target`) and an updated set of kernel modules. Without the check these would be overwritten when restoring the backup.

Do you feel like we want to cover this case or do you think it is too constructed? Can you think of any other case where we would not want to overwrite an existing directory of kernel modules?

**Comment by lideming** [comment]
I have added https://github.com/lideming/kernel-modules-hook-reflink/commit/ba3fa326be2bdba8b927d6505edf123f5d8c9c69 to check for `vmlinuz`.

> The only case I can think of right now that would warrant a check would be the installation of a package that provides modules for the currently running kernel, e.g. a self-built package that provides vmlinuz (to trigger the hook's Target) and an updated set of kernel modules. Without the check these would be overwritten when restoring the backup.

We are checking `vmlinuz` now, so the restoring won't run. Even if it runs, we use `cp` with `-n` (do not overwrite). So I think it's okay in this case?

**Comment by hrdl-github** [comment]
I guess this way we even support the exotic case of a linux package removing some modules that should not be restored. I think this is more than enough for now.

**Pull request merged**
